name: Owl Master Booking
favicon: null
layout_spectrum: 0.54928
typography_spectrum: 0.8865780378691852
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5d35b'
    - '#b8b8b8'
    - '#050505'
    - '#373737'
    - '#626262'
  brandStrength: 0.47924362146295607
  lightness: 0.2679374546278268
  saturation: 0.001653454266488552
  rhythmicContrast: 0.1876974713522941
purpose: []
